name: Docker
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx ğŸ‹
        uses: docker/setup-buildx-action@v3
      - name: Build Docker âš’ï¸
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: agda-mugen:edge
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Check agda-mugen ğŸ”
        run: docker run agda-mugen:edge
